### PR TITLE
Pometheus

### PR DESCRIPTION
**Pull request by PavloTarnovetskyi**
What is this change?

updated script that substitute public IP EC2 instance into prometheus.yml

**Why is this important?**
server monitoring infrastructure automatization

**How this has been tested?**

manually

**How can this be rolled back?**

Rollback can be performed by reverting these changes in source control and redeploying via standard deployment mechanisms. This change is safe to roll back.

**Are there any security risks introduced by this change?**

### CODE REVIEW

**Comment by nos373737** [comment]
Why you decide to swith script into Jenkins? @PavloTarnovetskyi

**Comment by PavloTarnovetskyi** [comment]
I decided to switch the script to Jenkinsfile because Jenkins didn`t run it correctly and I used Pipeline Syntax to modify the script for Jenkins, and now it works well.

**Comment by nos373737** [comment]
> I decided to switch the script to Jenkinsfile because Jenkins didn`t run it correctly and I used Pipeline Syntax to modify the script for Jenkins, and now it works well.

Why it is not working with a script?

**Comment by PavloTarnovetskyi** [comment]
When I ran the script in the terminal, it worked well.  In Jenkinsfile output was like on the screenshot.

**Comment by PavloTarnovetskyi** [comment]
Screenshot 2022-10-04 at 13 56 18

**Comment by vkuslui** [comment]
Hello, @PavloTarnovetskyi.
What does it mean ?
```
No such file or directory
``` 
I think it will be better to resolve this error for using the script for this step

**Comment by nos373737** [comment]
> Hello, @PavloTarnovetskyi. What does it mean ?
> 
> ```
> No such file or directory
> ```
> 
> I think it will be better to resolve this error for using the script for this step

Yep, fully agree. The better way is to use script in this case instead of copying code to the pipeline

**Pull request closed without merging**
